package com.setupmatch



import com.setupmatch.allocation.AllocationOutcome

import com.setupmatch.allocation.EquipmentCandidate

import com.setupmatch.allocation.HungarianAllocator

import com.setupmatch.allocation.PolicySlot

import com.setupmatch.api.CreateAllocationRequest

import com.setupmatch.api.toPolicySlots

import com.setupmatch.domain.PolicySlotJson

import com.setupmatch.domain.EquipmentType

import com.setupmatch.service.AllocationService

import com.setupmatch.service.EquipmentAllocationLoader

import org.junit.jupiter.api.AfterAll

import org.junit.jupiter.api.Assertions.assertTrue

import org.junit.jupiter.api.BeforeAll

import org.junit.jupiter.api.Test

import org.junit.jupiter.api.TestInstance

import org.springframework.beans.factory.annotation.Autowired

import org.springframework.boot.test.context.SpringBootTest

import org.springframework.jdbc.core.BatchPreparedStatementSetter

import org.springframework.jdbc.core.JdbcTemplate

import org.springframework.transaction.PlatformTransactionManager

import org.springframework.transaction.support.TransactionTemplate

import java.math.BigDecimal

import java.nio.file.Files

import java.nio.file.Path

import java.nio.file.Paths

import java.sql.PreparedStatement

import java.time.Instant

import java.time.LocalDate

import java.util.UUID

import kotlin.system.measureTimeMillis



@SpringBootTest

@TestInstance(TestInstance.Lifecycle.PER_CLASS)

class AllocationPerformanceIT {



    @Autowired

    private lateinit var jdbcTemplate: JdbcTemplate



    @Autowired

    private lateinit var equipmentAllocationLoader: EquipmentAllocationLoader



    @Autowired

    private lateinit var allocationService: AllocationService



    @Autowired

    private lateinit var transactionManager: PlatformTransactionManager



    private lateinit var benchmarkCandidates: List<EquipmentCandidate>

    private lateinit var benchmarkPolicies: List<BenchmarkPolicy>

    private lateinit var representativePolicy: BenchmarkPolicy



    private var selectLockedMs = 0L

    private var singleMatcherMs = 0L

    private var allocatorHungarianMs = 0L

    private var endToEndSingleMs = 0L

    private var endToEndTenPoliciesMs = 0L



    @BeforeAll

    fun seedInventory() {

        jdbcTemplate.execute("DELETE FROM allocation_line")

        jdbcTemplate.execute("DELETE FROM allocation_request")

        jdbcTemplate.execute("DELETE FROM equipment")



        val rows = buildSeedRows(TOTAL_ITEMS)

        val batchSize = 500

        rows.chunked(batchSize).forEach { chunk ->

            jdbcTemplate.batchUpdate(

                """

                INSERT INTO equipment (id, type, brand, model, state, condition_score, purchase_date)

                VALUES (?, ?, ?, ?, 'available', ?, ?)

                """.trimIndent(),

                object : BatchPreparedStatementSetter {

                    override fun setValues(ps: PreparedStatement, index: Int) {

                        val row = chunk[index]

                        ps.setObject(1, row.id)

                        ps.setString(2, row.type)

                        ps.setString(3, row.brand)

                        ps.setString(4, row.model)

                        ps.setBigDecimal(5, row.conditionScore)

                        ps.setObject(6, row.purchaseDate)

                    }



                    override fun getBatchSize(): Int = chunk.size

                },

            )

        }



        benchmarkPolicies = benchmarkPolicyDefinitions()

        representativePolicy = benchmarkPolicies.first()

    }



    @AfterAll

    fun writeOptimizationReport() {

        val specDir = resolveSpecDir()

        Files.createDirectories(specDir)



        val report = buildString {

            appendLine("# Allocation performance optimization")

            appendLine()

            appendLine("Generated by `AllocationPerformanceIT` at ${Instant.now()}.")

            appendLine()

            appendLine("## Benchmark setup")

            appendLine()

            appendLine("- Inventory: **$TOTAL_ITEMS** available equipment rows ($ITEMS_PER_TYPE per type).")

            appendLine("- Monitor pool includes a **competing-slots** shape: **one** high-condition monitor (0.86), the rest ≤ 0.77.")

            appendLine("- Policies: **${benchmarkPolicies.size}** allocations, **$SLOTS_PER_POLICY slots** each (5 devices per kit).")

            appendLine("- Production matcher: **Hungarian** (`HungarianAllocator.allocate`), parallel by equipment type.")

            appendLine("- Warmup: $WARMUP rounds; measured: $ITERATIONS rounds (median ms).")

            appendLine("- Full test suite: run `scripts/run-backend-tests.ps1` or `./gradlew test` (see **Test suite** below).")

            appendLine()

            appendLine("## Transaction overview")

            appendLine()

            appendLine("Each `POST /allocations` runs in **one database transaction** (`@Transactional` on `AllocationService.create`).")

            appendLine("Steps: **SELECT + lock** → **calculate in memory** → **INSERT/UPDATE** → **SELECT detail** → **COMMIT**.")

            appendLine()

            appendLine("---")

            appendLine()

            appendLine("## Step 1: SELECT (lock candidates)")

            appendLine()

            appendLine("Load only rows that can satisfy **hard constraints**, then lock them until commit.")

            appendLine()

            appendLine("**Code:** `EquipmentAllocationLoader.loadAndLockAvailable()` → `PolicySlotFilters` builds per-type `min_condition` floors.")

            appendLine()

            appendLine("### Timing (representative 5-slot policy)")

            appendLine()

            appendLine("- Median locked SELECT: **${selectLockedMs} ms**")

            appendLine()

            appendLine("### Optimisations")

            appendLine()

            appendLine("- **Hard-constraint filtering in SQL** — rows below the per-type `min_condition` floor are not fetched or locked.")

            appendLine("- **Index `idx_equipment_available_type_condition_id`** — partial index on `(type, condition_score, id) WHERE state = 'available'` (`V4__allocation_fetch_index.sql`).")

            appendLine()

            appendLine("### Correctness")

            appendLine()

            appendLine("- `HardConstraintFetchIT`, `HardConstraintFailureTest`, `PolicySlotFiltersTest`.")

            appendLine()

            appendLine("---")

            appendLine()

            appendLine("## Step 2: Calculation (matcher)")

            appendLine()

            appendLine("Pure Kotlin in `HungarianAllocator.allocate()`. No SQL in this step.")

            appendLine()

            appendLine("1. Group policy slots by `EquipmentType`.")

            appendLine("2. For each type, run **maximum-weight bipartite matching** (Hungarian) on that type’s candidates (`parallelStream()`).")

            appendLine("3. Edge weight per slot/candidate pair:")

            appendLine()

            appendLine("```")

            appendLine("edge_weight = condition_score × 100 + brand_bonus + recency_bonus + tie_break")

            appendLine("```")

            appendLine()

            appendLine("### Per-allocation timing (matcher only, in-memory)")

            appendLine()

            appendLine("- **Median time for one allocation** (1 policy, $SLOTS_PER_POLICY slots): **${singleMatcherMs} ms**")

            appendLine()

            appendLine("### Matcher throughput (all ${benchmarkPolicies.size} policies, in-memory)")

            appendLine()

            appendLine("| Matcher | Median ms (10×) |")

            appendLine("|---------|----------------:|")

            appendLine("| Hungarian, parallel by type | **${allocatorHungarianMs}** |")

            appendLine()

            appendLine("### Correctness")

            appendLine()

            appendLine("- `CompetingMonitorsTest`, `HardConstraintFailureTest`, `PolicySlotFiltersTest`.")

            appendLine()

            appendLine("---")

            appendLine()

            appendLine("## Step 3: SAVE (persist allocation)")

            appendLine()

            appendLine("### Timing")

            appendLine()

            appendLine("- **Median end-to-end per allocation** (1 policy, rolled back): **${endToEndSingleMs} ms**")

            appendLine("- End-to-end all ${benchmarkPolicies.size} policies in one transaction (rolled back): **${endToEndTenPoliciesMs} ms**")

            appendLine()

            appendLine("### Correctness")

            appendLine()

            appendLine("- `AllocationFlowIT`, `CancelReleasesEquipmentIT`, `QaScenariosIT`, `EquipmentListIT`.")

            appendLine()

            appendLine("---")

            appendLine()

            appendLine("## Test suite")

            appendLine()

            val suiteStatus = System.getProperty("test.suite.status") ?: "Run `./gradlew test` to refresh (see CI)."

            appendLine(suiteStatus)

            appendLine()

            appendLine("## Policies used in benchmark")

            appendLine()

            benchmarkPolicies.forEachIndexed { index, policy ->

                appendLine("${index + 1}. `${policy.name}`")

            }

        }



        Files.writeString(specDir.resolve("optimization.md"), report)

    }



    @Test

    fun `benchmark allocation with five thousand items and ten five-slot policies`() {

        val representativeSlots = representativePolicy.slots



        repeat(WARMUP) {

            loadAndLock(representativeSlots)

            benchmarkCandidates = loadAndLock(representativeSlots).map { it.toCandidate() }

            runSingleHungarianMatcher()

            runAllPoliciesHungarian()

        }



        selectLockedMs = medianMillis(ITERATIONS) {

            loadAndLock(representativeSlots)

        }



        benchmarkCandidates = loadAndLock(representativeSlots).map { it.toCandidate() }



        singleMatcherMs = medianMillis(ITERATIONS) { runSingleHungarianMatcher() }

        allocatorHungarianMs = medianMillis(ITERATIONS) { runAllPoliciesHungarian() }

        for (policy in benchmarkPolicies) {

            val outcome = HungarianAllocator.allocate(policy.slots, benchmarkCandidates)

            assertTrue(outcome is AllocationOutcome.Success, "hungarian failed: ${policy.name}")

        }



        endToEndSingleMs = medianMillis(ITERATIONS) {

            runSingleEndToEndWithRollback(representativePolicy)

        }

        endToEndTenPoliciesMs = medianMillis(ITERATIONS) {

            runAllEndToEndWithRollback()

        }

    }



    private fun runSingleHungarianMatcher() {

        val outcome = HungarianAllocator.allocate(representativePolicy.slots, benchmarkCandidates)

        assertTrue(outcome is AllocationOutcome.Success)

    }



    private fun runAllPoliciesHungarian() {

        for (policy in benchmarkPolicies) {

            val outcome = HungarianAllocator.allocate(policy.slots, benchmarkCandidates)

            assertTrue(outcome is AllocationOutcome.Success)

        }

    }



    private fun runSingleEndToEndWithRollback(policy: BenchmarkPolicy) {

        TransactionTemplate(transactionManager).execute { status ->

            allocationService.create(

                CreateAllocationRequest(

                    employeeId = "perf-single-${UUID.randomUUID()}",

                    policy = policy.requestPolicy,

                ),

            )

            status.setRollbackOnly()

            null

        }

    }



    private fun runAllEndToEndWithRollback() {

        TransactionTemplate(transactionManager).execute { status ->

            for (policy in benchmarkPolicies) {

                allocationService.create(

                    CreateAllocationRequest(

                        employeeId = "perf-${policy.name}-${UUID.randomUUID()}",

                        policy = policy.requestPolicy,

                    ),

                )

            }

            status.setRollbackOnly()

            null

        }

    }



    private fun loadAndLock(slots: List<PolicySlot>) =

        TransactionTemplate(transactionManager).execute {

            equipmentAllocationLoader.loadAndLockAvailable(slots)

        } ?: emptyList()



    private fun com.setupmatch.domain.EquipmentEntity.toCandidate() = EquipmentCandidate(

        id = id,

        type = type,

        brand = brand,

        model = model,

        conditionScore = conditionScore,

        purchaseDate = purchaseDate,

    )



    private fun medianMillis(iterations: Int, block: () -> Unit): Long {

        val samples = List(iterations) { measureTimeMillis { block() }.toDouble() }.sorted()

        return samples[samples.size / 2].toLong()

    }



    private fun resolveSpecDir(): Path = Paths.get("build/performance")



    private data class BenchmarkPolicy(

        val name: String,

        val requestPolicy: List<PolicySlotJson>,

    ) {

        val slots: List<PolicySlot> = requestPolicy.toPolicySlots()

    }



    private fun benchmarkPolicyDefinitions(): List<BenchmarkPolicy> = listOf(

        trapPolicy("trap-monitors-first-080", 0.80),

        trapPolicy("trap-monitors-first-075", 0.75),

        trapPolicy("trap-monitors-first-085", 0.85),

        trapPolicy("trap-monitors-first-082", 0.82),

        trapPolicy("trap-monitors-first-078", 0.78),

        kitPolicy("kit-brands-apple-dell", "Apple", "Dell"),

        kitPolicy("kit-brands-lenovo-samsung", "Lenovo", "Samsung"),

        kitPolicy("kit-brands-dell-lg", "Dell", "LG"),

        kitPolicy("kit-minimal-mins", null, null, laptopMin = 0.70, monitorMin = 0.65),

        kitPolicy("kit-strict-mins", null, null, laptopMin = 0.88, monitorMin = 0.82),

    )



    private fun trapPolicy(name: String, constrainedMonitorMin: Double): BenchmarkPolicy {

        return BenchmarkPolicy(

            name = name,

            requestPolicy = listOf(

                PolicySlotJson(EquipmentType.monitor),

                PolicySlotJson(EquipmentType.monitor, min_condition = constrainedMonitorMin),

                PolicySlotJson(EquipmentType.main_computer, min_condition = 0.75, preferred_brand = "Apple"),

                PolicySlotJson(EquipmentType.keyboard, min_condition = 0.60),

                PolicySlotJson(EquipmentType.mouse, preferred_brand = "Logitech"),

            ),

        )

    }



    private fun kitPolicy(

        name: String,

        laptopBrand: String?,

        monitorBrand: String?,

        laptopMin: Double = 0.75,

        monitorMin: Double = 0.70,

    ): BenchmarkPolicy {

        return BenchmarkPolicy(

            name = name,

            requestPolicy = listOf(

                PolicySlotJson(EquipmentType.main_computer, min_condition = laptopMin, preferred_brand = laptopBrand),

                PolicySlotJson(EquipmentType.monitor, min_condition = monitorMin, preferred_brand = monitorBrand),

                PolicySlotJson(EquipmentType.keyboard, min_condition = 0.55),

                PolicySlotJson(EquipmentType.mouse),

                PolicySlotJson(EquipmentType.monitor, min_condition = 0.72),

            ),

        )

    }



    private data class SeedRow(

        val id: UUID,

        val type: String,

        val brand: String,

        val model: String,

        val conditionScore: BigDecimal,

        val purchaseDate: LocalDate,

    )



    private fun buildSeedRows(totalItems: Int): List<SeedRow> {

        val brands = listOf("Apple", "Dell", "Lenovo", "Logitech", "LG", "Samsung", "Keychron", "Razer")

        val types = EquipmentType.entries

        val perType = totalItems / types.size



        return types.flatMap { type ->

            (0 until perType).map { index ->

                val condition = when (type) {

                    EquipmentType.monitor -> monitorCondition(index, perType)

                    else -> genericCondition(index, perType)

                }

                SeedRow(

                    id = UUID.nameUUIDFromBytes("perf-$type-$index".toByteArray()),

                    type = type.name,

                    brand = brands[(index + type.ordinal) % brands.size],

                    model = "${type.name}-$index",

                    conditionScore = condition,

                    purchaseDate = when (type) {
                        EquipmentType.monitor -> if (index == 0) {
                            LocalDate.of(2024, 6, 1)
                        } else {
                            LocalDate.of(2019, 1, 1).plusDays(index.toLong())
                        }
                        else -> LocalDate.of(2020, 1, 1).plusDays((index + type.ordinal * 7).toLong())
                    },

                )

            }

        }

    }



    private fun monitorCondition(index: Int, perType: Int): BigDecimal {
        if (index == 0) {
            return BigDecimal.valueOf(0.86)
        }

        val lowIndex = index - 1
        val lowSpan = perType - 2
        val step = if (lowSpan > 0) 0.22 / lowSpan else 0.0

        return BigDecimal.valueOf(0.55 + lowIndex * step).coerceAtMost(BigDecimal.valueOf(0.77))
    }



    private fun genericCondition(index: Int, perType: Int): BigDecimal {

        val step = if (perType > 1) 0.44 / (perType - 1) else 0.0



        return BigDecimal.valueOf(0.55 + index * step)

    }



    companion object {

        private const val TOTAL_ITEMS = 5000

        private const val ITEMS_PER_TYPE = TOTAL_ITEMS / 4

        private const val SLOTS_PER_POLICY = 5


        private const val WARMUP = 2

        private const val ITERATIONS = 5

    }

}


